### PR TITLE
Fix undefined chart node when switching commits in profiler

### LINKED ISSUE #267: Error: "Cannot read property 'treeBaseDuration' of undefined"
This happened when I clicked on a commit while browsing a profile I recorded

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.0-a04dbd0

Call stack: at chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:56:271235
    at Object.useMemo (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:61084)
    at useMemo (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:30:5137)
    at qi (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:56:271194)
    at Ia (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:56417)
    at ci (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:63273)
    at xl (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:96620)
    at vl (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:81540)
    at Al (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:79166)
    at e (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:77886)

Component stack: in qi
    in div
    in t
    in div
    in $i
    in Suspense
    in div
    in div
    in div
    in us
    in di
    in Unknown
    in Ga
    in Unknown
    in div
    in div
    in hi
    in Pe
    in We
    in Os

### PR DESCRIPTION
**Pull request by lucasecdb**
fixes #267

### CODE REVIEW

File: src/devtools/views/Profiler/CommitFlamegraph.js [hunk 1]
```diff
@@ -123,9 +123,13 @@ function CommitFlamegraph({
...
     if (selectedFiberID !== null) {
-      chartNode = ((chartData.rows[selectedChartNodeIndex].find(
+      const foundChartNode = chartData.rows[selectedChartNodeIndex].find(
         chartNode => chartNode.id === selectedFiberID
-      ): any): ChartNode);
+      );
+
+      if (foundChartNode !== undefined) {
+        chartNode = foundChartNode;
+      }
```
Comment (bvaughn) [inline src/devtools/views/Profiler/CommitFlamegraph.js]: Hm, so the problem was that we were assigning an unexpected `undefined` value

Comment (lucasecdb) [reply src/devtools/views/Profiler/CommitFlamegraph.js]: exactly. the case was that I had a selected a node in one commit, but on subsequent commits the tree had a modification on the parent components (adding another wrapper to the whole tree), so the selected node ID wasn't in the tree anymore.

Comment (bvaughn) [reply src/devtools/views/Profiler/CommitFlamegraph.js]: Nice fix
